### ISSUE TITLE
Explicit Boolean Features Cannot be Used Currently

### ISSUE THREAD

**Issue by SundermannC** [Universal-Variability-Language/uvl-lsp#53]
Typed features can be either String, Real, Integer or Boolean. If not stated, features are always considered to be of the Boolean type. However, UVL also supports explicitly stating a Boolean feature with the same syntax as the other types.

![image](https://github.com/Universal-Variability-Language/uvl-lsp/assets/24757266/37f3072d-e371-4588-bfd6-41e677feb868)

Boolean is also not shown as option for auto-completions.

**Comment by SundermannC** [comment]
This problem may be related to the name collision with the language level.

**Comment by pascalfoerster** [comment]
The problem lies in the grammar. The grammar is written in such a way that the syntax check always recognizes Boolean as major_lvl, even if it is not under the includes keyword. 
I think there are two possible solutions. 
The easier and faster one would be to rename the keyword for the Boolean type feature, for example to Boolean type.
The other would be to change the grammar to make it unambiguous.
@SundermannC , which solution do you prefer?
