### ISSUE TITLE
Integration of UVLS in Additional IDEs

### ISSUE THREAD

**Issue by SundermannC** [Universal-Variability-Language/uvl-lsp#6]
As of now, UVLS is integrated in:

- [x] Visual Studio Code
- [x] NeoVim

It would be great to have UVLS integrated into additional IDEs to allow more widespread usage.

**Comment by TobiUUlm** [comment]
An integration into Notepad++ is quite easy to achieve due to the great [NppLSP](https://github.com/Ekopalypse/NppLspClient) plugin.  
I created some UDL (Language Highlights) for Notepad++. We can talk about integrating this into the [global collection of UDLs](https://github.com/notepad-plus-plus/userDefinedLanguages/tree/master).  

Some features (like TAUT/UNSAT) don't seem to work. Maybe we push it with non-recognized priorities.

Other configuration files + explanation will follow in next commit.

**Comment by TobiUUlm** [comment]
Here is a list of all natively supported tools to choose from:  
https://microsoft.github.io/language-server-protocol/implementors/tools/
